version: '3.1'

services:
  db:
    build: .
    container_name: api-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes: # persiste os dados em um arquivo
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projectdb